### ISSUE TITLE
Run with xlmr_base erro!

### ISSUE THREAD

**Issue by JXZe** [jzbjyb/X-FACTR#5]
Hello,

When I run the code with the following commands:

`python scripts/probe.py --model xlmr_base --lang en --pred_dir $OUTPUT`

I met the following erro:

```
bug for pid P19
CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
Traceback (most recent call last):
  File "scripts/probe.py", line 643, in iter
    reprob=self.args.reprob, beam_size=args.beam_size)
  File "scripts/probe.py", line 906, in iter_decode_beam_search
    logit = model_prediction_wrap(model, inp_tensor, attention_mask)
  File "scripts/probe.py", line 108, in model_prediction_wrap
    logit = model(inp_tensor, attention_mask=attention_mask)[0]
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/transformers/modeling_roberta.py", line 243, in forward
    inputs_embeds=inputs_embeds,
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/transformers/modeling_bert.py", line 806, in forward
    encoder_attention_mask=encoder_extended_attention_mask,
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/transformers/modeling_bert.py", line 423, in forward
    hidden_states, attention_mask, head_mask[i], encoder_hidden_states, encoder_attention_mask
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/transformers/modeling_bert.py", line 384, in forward
    self_attention_outputs = self.attention(hidden_states, attention_mask, head_mask)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/transformers/modeling_bert.py", line 330, in forward
    hidden_states, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/transformers/modeling_bert.py", line 232, in forward
    mixed_query_layer = self.query(hidden_states)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/functional.py", line 1676, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
Traceback (most recent call last):
  File "scripts/probe.py", line 1141, in <module>
    probe_iter.iter(pids=set(args.pids.strip().split(',')) if args.pids is not None else None)
  File "scripts/probe.py", line 765, in iter
    raise e
  File "scripts/probe.py", line 643, in iter
    reprob=self.args.reprob, beam_size=args.beam_size)
  File "scripts/probe.py", line 906, in iter_decode_beam_search
    logit = model_prediction_wrap(model, inp_tensor, attention_mask)
  File "scripts/probe.py", line 108, in model_prediction_wrap
    logit = model(inp_tensor, attention_mask=attention_mask)[0]
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/transformers/modeling_roberta.py", line 243, in forward
    inputs_embeds=inputs_embeds,
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/transformers/modeling_bert.py", line 806, in forward
    encoder_attention_mask=encoder_extended_attention_mask,
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/transformers/modeling_bert.py", line 423, in forward
    hidden_states, attention_mask, head_mask[i], encoder_hidden_states, encoder_attention_mask
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/transformers/modeling_bert.py", line 384, in forward
    self_attention_outputs = self.attention(hidden_states, attention_mask, head_mask)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/transformers/modeling_bert.py", line 330, in forward
    hidden_states, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/transformers/modeling_bert.py", line 232, in forward
    mixed_query_layer = self.query(hidden_states)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/anaconda/envs/xfactr/lib/python3.7/site-packages/torch/nn/functional.py", line 1676, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`


```

And I can run with mbert_base successfully. How to fix it?

Thanks!

**Comment by JanAthmer** [comment]
Hey, we also have this issue. Have you found a fix by any chance?
